### ISSUE TITLE
risk-premia-notebook.Rmd [Bug report]

### ISSUE THREAD

**Issue by GIANTRAIN** [Robot-Wealth/risk-premia-app#8]
Line 67-82:
```
p <- prices %>% 
  arrange(date) %>%
  group_by(ticker) %>%
  mutate(totalreturns = ((closeadjusted) / dplyr::lag(closeadjusted)) - 1) %>%
  na.omit() %>%
  mutate(cumreturns = cumprod(1+totalreturns)) %>% 
  ggplot(aes(x=date, y = cumreturns, color = ticker)) + geom_line()
  
returns %>% 
  filter(ticker == "GLD") %>% 
  select(ticker, date, totalreturns) %>% 
  inner_join(p, by = c("ticker", "date")) %>% 
  mutate(diff = totalreturns.x - totalreturns.y) %>% 
  ggplot(aes(x = date, y = diff)) + geom_line()
```

1.  
the first chunk of code about the "p", the last line：
"%>% 
  ggplot(aes(x=date, y = cumreturns, color = ticker)) + geom_line()"  
need to be remove.
Otherwise, the second chunk of code would be got an error, because now "p" is a plot instead of a data frame.

2.
p's "totalreturns", is calculated by the field "closeadjusted", this field is from the source data.
If you change the ticker to "TLT", you would found 1 big data spike, this mean maybe the source data have some problem.

3.
Line 87-93:

```
returns %>%
  mutate(checkreturns = adjclose / lag(adjclose) - 1) %>%
  mutate(check = totalreturns - checkreturns) %>%
  na.omit() %>% 
  ggplot(aes(x = date, y = check)) + geom_line() + facet_wrap(~ticker)
```

This time the checkreturns is calculate by adjclose, which is our custom field not "closeadjusted" from data source.
So the check logic isn't consistent with those from Line 67-82.
So the "TLT" hasn't shown any spike this time.

**Comment by robotmasterkris** [comment]
@GIANTRAIN which file does this relate to?

**Comment by robotmasterkris** [comment]
I've resolved issue 1. Noted issue 2. Issue 3 requires no action - we're comparing returns calculated from the two different sources. 

Many thanks for contributing!

**Comment by GIANTRAIN** [comment]
risk-premia-app/background/risk-premia-notebook.Rmd







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kris Longmore"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 下午2:40
收件人:&nbsp;"Robot-Wealth/risk-premia-app"<risk-premia-app@noreply.github.com&gt;;
抄送:&nbsp;"JiangTianYu"<1009485906@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Robot-Wealth/risk-premia-app] risk-premia-notebook.Rmd [Bug report] (#8)





 
@GIANTRAIN which file does this relate to?
